name: "Bug Fix"
description: "Use this template to report and fix a bug"
title: "fix: "
labels: ["bug", "fix"]
body:
  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "Briefly describe the bug"
      placeholder: "MessageActions component not rendering correctly"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Explain how to reproduce the issue"
      placeholder: |
        1. Go to the chat page
        2. Send a message
        3. Observe error in console
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened"
      placeholder: "MessageActions renders without errors."

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happens"
      placeholder: "Component crashes when loading the chat page."

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "Add details like OS, browser, Node version, etc."
      placeholder: "macOS 14, Chrome 119, Node 18"

  - type: textarea
    id: logs
    attributes:
      label: "Logs or Screenshots"
      description: "Attach relevant logs or screenshots"
      placeholder: "Paste logs or attach screenshots"
